use_cuda: True
dataset: 'kspon'
dataset_path: ''
transcripts_path: "C:/Users/User/PycharmProjects/kospeach_Project/kospeech/dataset/kspon/transcripts.txt"
model_path: ''
output_unit: 'character'
batch_size: 32
num_workers: 4
print_every: 20
decode: 'greedy'
k: 3